POST http://localhost:4000/api/todos
Content-Type: application/json
Accept: application/json

{
  "title" : "",
  "description" : ""
}

### Create

GET http://localhost:4000/api/todos
Content-Type: application/json
Accept: application/json

### Get List


PATCH http://localhost:4000/api/todos/60b9f90e-8f90-40b5-b40b-da15d1fad561
Content-Type: application/json
Accept: application/json

{
  "completed": true
}

### Create

DELETE http://localhost:4000/api/todos/salah
Content-Type: application/json
Accept: application/json


### Create