POST http://localhost:4000/api/todos
Content-Type: application/json
Accept: application/json

{
  "title" : "Belanja Vape",
  "description" : "Beli Liquid, Ganti Kawat"
}

### Create

GET http://localhost:4000/api/todos
Content-Type: application/json
Accept: application/json

### Get List


PATCH http://localhost:4000/api/todos/5eaca8b0-edcc-4c0e-a1f4-a0c8f2122839
Content-Type: application/json
Accept: application/json

{
  "completed": true
}

### Create

DELETE http://localhost:4000/api/todos/dda41866-9ec7-437c-b327-ccbdb7fea19c
Content-Type: application/json
Accept: application/json


### Create